import os
import datetime
import argparse
import json


# Load config options
parser = argparse.ArgumentParser()
parser.add_argument("--dataset", type=str, default="caltech101", nargs='*', help="Dataset name")
parser.add_argument("--trainer", type=str, default="CoOp",
                    help="Name of trainer, e.g, CoOp, FVGPT_CoOp")
parser.add_argument("--seed_list", type=int, default=1, nargs='*', help="A list of seeds")
parser.add_argument("--sub_class", type=str, default="new", help="For BASE or NEW class")
parser.add_argument("--add_opts", type=str, default="", help="Additional options")

# [FVGPT] New Configs
parser.add_argument("--lambda_base", type=float, default=1.0, help="cfg.TRAINER.AMPT.RDBOOST_LAMBDA_D")
parser.add_argument("--lambda_new", type=float, default=1.0, help="cfg.TRAINER.AMPT.BDPC_LAMBDA")
args = parser.parse_args()


datasets = args.dataset
trainer = args.trainer  # backbone models (CoOp / KgCoOp / PromptSRC / MMRL)
seed_list = args.seed_list
subsample_class = args.sub_class  # base / new / all

lambda_base = args.lambda_base
lambda_new = args.lambda_new
add_opts = args.add_opts  # Optional extra arguments for overriding, e.g., "[[arg1,new_val1],[arg2,new_val2],...]"; wrap the nested list in quotes.


# Given a nested-list string like "[[arg1,new_val1],[arg2,new_val2],...]", first parse it back into a nested list, then use it to override the original values passed by the main program
def opt_override(opt_list):
    if opt_list != "":
        nested_list = json.loads(opt_list)
        for arg_and_value in nested_list:
            globals()[arg_and_value[0]] = arg_and_value[1]


# If log.txt already exists before training, rename the existing file to avoid conflicts with the log.txt generated by this training/fine-tuning run.
def detect_and_rename_existing_log(output_dir):
    log_txt = output_dir + "/log.txt"
    if os.path.exists(log_txt):
        time_for_name = datetime.datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
        new_log_txt = output_dir + "/log-" + str(time_for_name) + ".txt"
        os.rename(log_txt, new_log_txt)


def run_and_extract_result(command, output_dir):
    result_lines = []
    if "ERROR" in command:
        result_lines = ["ERROR \n", "ERROR \n", "ERROR \n", "ERROR \n", "ERROR \n"]
    else:
        os.system(command)  # Run the command
        log_txt = output_dir + "/log.txt"  # After train/val completes, read log.txt in the corresponding directory
        if os.path.exists(log_txt):
            with open(log_txt, "r") as f:
                lines = f.readlines()
                result_lines = lines[-6:]  # Extract the last 6 lines (total/correct/acc, etc.)
    return result_lines


def get_dataset_config(target_dataset):
    rootx = ""
    dataset_configx = ""

    if target_dataset == "caltech101":
        rootx = "DATA/caltech-101"
        dataset_configx = "configs/datasets/caltech101.yaml"

    elif target_dataset == "stanford_cars":
        rootx = "DATA/stanford_cars"
        dataset_configx = "configs/datasets/stanford_cars.yaml"

    elif target_dataset == "sun397":
        rootx = "DATA/sun-397"
        dataset_configx = "configs/datasets/sun397.yaml"

    elif target_dataset == "food101":
        rootx = "DATA/food101"
        dataset_configx = "configs/datasets/food101.yaml"

    elif target_dataset == "dtd":
        rootx = "DATA/dtd/dtd"
        dataset_configx = "configs/datasets/dtd.yaml"

    elif target_dataset == "eurosat":
        rootx = "DATA/eurosat"
        dataset_configx = "configs/datasets/eurosat.yaml"

    elif target_dataset == "flowers102":
        rootx = "DATA/flowers-102"
        dataset_configx = "configs/datasets/oxford_flowers.yaml"

    elif target_dataset == "oxford_pets":
        rootx = "DATA/oxford_pets"
        dataset_configx = "configs/datasets/oxford_pets.yaml"

    elif target_dataset == "ucf101":
        rootx = "DATA/ucf101"
        dataset_configx = "configs/datasets/ucf101.yaml"

    elif target_dataset == "fgvc_aircraft":
        rootx = "DATA/fgvc_aircraft/fgvc-aircraft-2013b"
        dataset_configx = "configs/datasets/fgvc_aircraft.yaml"

    elif target_dataset == "imagenet":
        rootx = "DATA/imagenet-1k"
        dataset_configx = "configs/datasets/imagenet.yaml"

    return rootx, dataset_configx


def get_trainer_configs(target_trainer):
    config_filex = ""
    baseline_epoch = 0
    baseline_backbone = ""

    if target_trainer == "CoOp" or target_trainer == "FVGPT_CoOp":
        config_filex = "vit_b16_ep10"
        baseline_epoch = 10
        baseline_backbone = "prompt_learner"
    elif target_trainer == "PromptSRC" or target_trainer == "FVGPT_PromptSRC":
        config_filex = "vit_b16_c2_ep10_batch32_4+4ctx"
        baseline_epoch = 10
        baseline_backbone = "VLPromptLearner"
    elif target_trainer == "KgCoOp" or target_trainer == "FVGPT_KgCoOp":
        config_filex = "vit_b16_ep10_ctxv1_bs4_lr35"
        baseline_epoch = 10
        baseline_backbone = "prompt_learner"
    elif target_trainer == "MMRL" or target_trainer == "FVGPT_MMRL":
        config_filex = "vit_b16"
        baseline_epoch = 10
        baseline_backbone = "MultiModalRepresentationLearner"

    return config_filex, baseline_epoch, baseline_backbone


def basic_paths(dataset, trainer):
    config_filex, _, _ = get_trainer_configs(trainer)
    config_file = "configs/trainers/" + trainer + "/" + config_filex + ".yaml"
    base_output_dir = "output/" + trainer + "/" + dataset + "/base/" + config_filex  # [Note] seed is not included
    new_output_dir = "output/" + trainer + "/" + dataset + "/new/" + config_filex  # [Note] seed is not included
    return config_file, base_output_dir, new_output_dir


# Start loop
for dataset in datasets:
    # Load all config options
    part_config_param, epoch, backbone_name = get_trainer_configs(trainer)
    root, dataset_config_file = get_dataset_config(dataset)
    config_file, base_output_dir, new_output_dir = basic_paths(dataset, trainer)

    opt_override(add_opts)

    # Build the command for each seed
    for seed in seed_list:
        # Build required paths; for FVGPT experiments, append hyperparameters to the directory for ablation studies
        if "FVGPT" in base_output_dir:
            full_base_path = base_output_dir + "-b" + str(lambda_base) + "-n" + str(lambda_new) + "/seed" + str(seed)
            ckpt_path = base_output_dir + "-b" + str(lambda_base) + "-n" + str(lambda_new) + "/seed" + str(seed) + "/" + backbone_name  # Used to check whether the checkpoint exists
            full_new_path = new_output_dir + "-b" + str(lambda_base) + "-n" + str(lambda_new) + "/seed" + str(seed)
        else:
            full_base_path = base_output_dir + "/seed" + str(seed)
            ckpt_path = base_output_dir + "/seed" + str(seed) + "/" + backbone_name  # Used to check whether the checkpoint exists
            full_new_path = new_output_dir + "/seed" + str(seed)

        final_output_dir = ""
        command = ""

        # Check whether a checkpoint exists
        if os.path.exists(ckpt_path):
            if subsample_class == "base":
                report = trainer.upper() + " Checkpoint detected (" + ckpt_path + ") in training phase, turning into val on [BASE] class"
                # If a previous log.txt exists in the val output directory, rename it
                detect_and_rename_existing_log(full_base_path)
                final_output_dir = full_base_path
                # Build the same command as base-class training, and run inference
                command = ("python train.py --root " + root + " --seed " + str(seed) + " --trainer " + trainer
                           + " --dataset-config-file " + dataset_config_file + " --config-file " + config_file
                           + " --output-dir " + full_base_path
                           + " DATASET.NUM_SHOTS 16"
                           + " TRAINER.COOP.N_CTX 4 TRAINER.COOP.CSC False TRAINER.COOP.CLASS_TOKEN_POSITION end"
                           + " TRAINER.AMPT.RDBOOST_LAMBDA_D " + str(lambda_base)
                           + " TRAINER.AMPT.BDPC_LAMBDA " + str(lambda_new)
                           + " DATASET.SUBSAMPLE_CLASSES " + subsample_class
                           )
            elif subsample_class == "new":
                report = trainer.upper() + " Checkpoint detected (" + ckpt_path + "), turning into val phase on [NEW] or [ALL] class"
                # If a previous log.txt exists in the val output directory, rename it
                detect_and_rename_existing_log(full_new_path)
                final_output_dir = full_new_path
                # Build inference command
                command = ("python train.py  --root " + root + " --seed " + str(seed) + " --trainer " + trainer
                           + " --dataset-config-file " + dataset_config_file + " --config-file " + config_file
                           + " --output-dir " + full_new_path + " --model-dir " + full_base_path
                           + " --load-epoch " + str(epoch) + " --eval-only DATASET.NUM_SHOTS 16"
                           + " TRAINER.COOP.N_CTX 4 TRAINER.COOP.CSC False TRAINER.COOP.CLASS_TOKEN_POSITION end"
                           + " TRAINER.AMPT.RDBOOST_LAMBDA_D " + str(lambda_base)
                           + " TRAINER.AMPT.BDPC_LAMBDA " + str(lambda_new)
                           + " DATASET.SUBSAMPLE_CLASSES " + subsample_class
                           )
            else:
                report = "ERROR!! This script only support BASE or NEW mode!"

            print("[FVGPT_TUNING_SCRIPT]: " + report)

        # If the expected path does not exist, run standard base-class training/inference
        else:
            final_output_dir = ""
            if subsample_class == "base":
                report = "Start training on BASELINE"
                print("[FVGPT_TUNING_SCRIPT]: " + report)
                detect_and_rename_existing_log(full_base_path)
                final_output_dir = full_base_path
                # Build the same command as base-class training, and run inference
                command = ("python train.py  --root " + root + " --seed " + str(seed) + " --trainer " + trainer
                           + " --dataset-config-file " + dataset_config_file + " --config-file " + config_file
                           + " --output-dir " + full_base_path
                           + " DATASET.NUM_SHOTS 16"
                           + " TRAINER.COOP.N_CTX 4 TRAINER.COOP.CSC False TRAINER.COOP.CLASS_TOKEN_POSITION end"
                           + " TRAINER.AMPT.RDBOOST_LAMBDA_D " + str(lambda_base)
                           + " TRAINER.AMPT.BDPC_LAMBDA " + str(lambda_new)
                           + " DATASET.SUBSAMPLE_CLASSES " + subsample_class
                           )
            elif subsample_class == "new":
                report = "ERROR!! CANNOT INFERENCE ON [NEW] CLASS WITHOUT [BASE] CHECKPOINT!!"
                print("[FVGPT_TUNING_SCRIPT]: " + report)
                command = "ERROR"
            else:
                report = "ERROR!! This script only support BASE or NEW mode!"
                print("[FVGPT_TUNING_SCRIPT]: " + report)
                command = "ERROR"

        # print("command: ", command, "\n final_output_dir: ", final_output_dir)  # [Debug]

        print("COMMAND: ", command)
        result = run_and_extract_result(command, final_output_dir)
        acc_info = report + "\n"
        for item in result:
            acc_info = acc_info + item
        time_now = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        result_info = ("[Time] " + str(time_now) + "\n === Results of " + trainer
                       + " on [" + subsample_class + "] setting: "
                       + dataset + ", " + config_file + ", seed " + str(seed) + " ==="
                       + "\n === lambda_base: " + str(lambda_base) + ", lambda_new: " + str(lambda_new) + " === \n"
                       + acc_info)

        with open("output/" + trainer + "/recorded_experiments.txt", "a") as file:
            file.write(result_info + "\n")
